// <auto-generated />
using System;
using AgileConfig.Server.Data.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgileConfig.Server.Data.EFCore.Migrations
{
    [DbContext(typeof(AgileConfigDbContext))]
    [Migration("20260311093621_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.App", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("agc_app", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.AppInheritanced", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("appid");

                    b.Property<string>("InheritancedAppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("inheritanced_appid");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("InheritancedAppId");

                    b.ToTable("agc_appInheritanced", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.Config", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EditStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Env")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("g");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("k");

                    b.Property<int>("OnlineStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "Env");

                    b.HasIndex("AppId", "Key", "Env");

                    b.ToTable("agc_config", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.ConfigPublished", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Env")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("g");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("k");

                    b.Property<DateTime?>("PublishTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishTimelineId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublishTimelineId");

                    b.HasIndex("AppId", "Env");

                    b.ToTable("agc_config_published", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.Function", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("agc_function", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "001",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add Application",
                            Name = "App.Add",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "002",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edit Application",
                            Name = "App.Edit",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "003",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delete Application",
                            Name = "App.Delete",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "004",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add Configuration",
                            Name = "Config.Add",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "005",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edit Configuration",
                            Name = "Config.Edit",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "006",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delete Configuration",
                            Name = "Config.Delete",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "007",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Publish Configuration",
                            Name = "Config.Publish",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "008",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rollback Configuration",
                            Name = "Config.Rollback",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "009",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add User",
                            Name = "User.Add",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "010",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edit User",
                            Name = "User.Edit",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "011",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delete User",
                            Name = "User.Delete",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "012",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add Node",
                            Name = "Node.Add",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "013",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delete Node",
                            Name = "Node.Delete",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "014",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View System Log",
                            Name = "SysLog.View",
                            SortIndex = 0
                        });
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.PublishDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EditStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Env")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishTimelineId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublishTimelineId");

                    b.ToTable("agc_publish_detail", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.PublishTimeline", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Env")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Log")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishUserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishUserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublishTime");

                    b.HasIndex("AppId", "Env");

                    b.ToTable("agc_publish_timeline", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("agc_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "001",
                            CreateTime = new DateTime(2026, 3, 11, 9, 36, 20, 708, DateTimeKind.Local).AddTicks(5147),
                            Description = "System Administrator",
                            IsSystem = true,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = "002",
                            CreateTime = new DateTime(2026, 3, 11, 9, 36, 20, 708, DateTimeKind.Local).AddTicks(5436),
                            Description = "System Operator",
                            IsSystem = true,
                            Name = "Operator"
                        });
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.RoleFunction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("RoleId");

                    b.ToTable("agc_role_function", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6c7ed036-1eb7-407c-a897-2d1a3bc8c9d2",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "001",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "fdd8ff78-c875-45ee-b881-11da11b46f39",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "002",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "9fa97f7d-6806-4d58-9981-1d0801bbae4b",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "003",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "b0c2f626-6d12-40fd-930d-d5fe0c3bbd56",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "004",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "6e2b69ca-3d9b-44db-b2df-6c818257a83f",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "005",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "409e3398-def2-4132-92f3-700ff7448b04",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "006",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "5bb6742b-8952-488c-b5ae-e69aef018867",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "007",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "e56a2262-504d-42a0-beb0-76bff86dfe7e",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "008",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "595cd020-0c55-46e7-8a81-811a3451b32b",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "009",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "08ed390e-ba8e-421b-a73d-35899646ba2b",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "010",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "4be2fe80-047b-4e27-b4c4-0351e483668a",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "011",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "446cb7b4-99b5-4f0d-818b-a980629dfb3a",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "012",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "4cfc7e2e-9138-4ae9-a529-beaf0fcf96e1",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "013",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "b913970b-81e1-4198-905b-d852de1a5057",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "014",
                            RoleId = "001"
                        });
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.ServerNode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastEchoTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("agc_server_node", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.ServiceInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartBeatMode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeartBeat")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaData")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RegisterTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegisterWay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "ServiceName");

                    b.ToTable("agc_service_info", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.Setting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("agc_setting", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.SysLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LogTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogType")
                        .HasMaxLength(256)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogTime");

                    b.ToTable("agc_sys_log", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("agc_user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            CreateTime = new DateTime(2026, 3, 11, 9, 36, 20, 706, DateTimeKind.Local).AddTicks(5170),
                            Password = "s7+8OVBvDjrupqv0jjamNQL9sszewpyqEv9cXnoJPfs=",
                            Salt = "66941967e7ac4e74b0d87a8b4439fe73",
                            Source = 0,
                            Status = 0,
                            Team = "",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.UserAppAuth", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Permission")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "UserId");

                    b.ToTable("agc_user_app_auth", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("agc_user_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3c13991d-c648-43e0-8323-e723242cc28e",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = "001",
                            UserId = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
