// <auto-generated />
using System;
using AgileConfig.Server.Data.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgileConfig.Server.Data.EFCore.Migrations
{
    [DbContext(typeof(AgileConfigDbContext))]
    [Migration("20260313073333_V1_10_Baseline")]
    partial class V1_10_Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.App", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Group")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("agc_app", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.AppInheritanced", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("appid");

                    b.Property<string>("InheritancedAppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("inheritanced_appid");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("InheritancedAppId");

                    b.ToTable("agc_appInheritanced", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.Config", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EditStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Env")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("g");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("k");

                    b.Property<int>("OnlineStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "Env");

                    b.HasIndex("AppId", "Key", "Env");

                    b.ToTable("agc_config", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.ConfigPublished", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Env")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("g");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("k");

                    b.Property<DateTime?>("PublishTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishTimelineId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublishTimelineId");

                    b.HasIndex("AppId", "Env");

                    b.ToTable("agc_config_published", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.Function", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("agc_function", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "001",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add Application",
                            Name = "App.Add",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "002",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edit Application",
                            Name = "App.Edit",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "003",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delete Application",
                            Name = "App.Delete",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "004",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add Configuration",
                            Name = "Config.Add",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "005",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edit Configuration",
                            Name = "Config.Edit",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "006",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delete Configuration",
                            Name = "Config.Delete",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "007",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Publish Configuration",
                            Name = "Config.Publish",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "008",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rollback Configuration",
                            Name = "Config.Rollback",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "009",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add User",
                            Name = "User.Add",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "010",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Edit User",
                            Name = "User.Edit",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "011",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delete User",
                            Name = "User.Delete",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "012",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add Node",
                            Name = "Node.Add",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "013",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Delete Node",
                            Name = "Node.Delete",
                            SortIndex = 0
                        },
                        new
                        {
                            Id = "014",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "View System Log",
                            Name = "SysLog.View",
                            SortIndex = 0
                        });
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.PublishDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EditStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Env")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishTimelineId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublishTimelineId");

                    b.ToTable("agc_publish_detail", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.PublishTimeline", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Env")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Log")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishUserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishUserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublishTime");

                    b.HasIndex("AppId", "Env");

                    b.ToTable("agc_publish_timeline", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("agc_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "001",
                            CreateTime = new DateTime(2026, 3, 11, 9, 36, 21, 0, DateTimeKind.Utc),
                            Description = "System Administrator",
                            IsSystem = true,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = "002",
                            CreateTime = new DateTime(2026, 3, 11, 9, 36, 21, 0, DateTimeKind.Utc),
                            Description = "System Operator",
                            IsSystem = true,
                            Name = "Operator"
                        });
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.RoleFunction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.HasIndex("RoleId");

                    b.ToTable("agc_role_function", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "rf-001",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "001",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-002",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "002",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-003",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "003",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-004",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "004",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-005",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "005",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-006",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "006",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-007",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "007",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-008",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "008",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-009",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "009",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-010",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "010",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-011",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "011",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-012",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "012",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-013",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "013",
                            RoleId = "001"
                        },
                        new
                        {
                            Id = "rf-014",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FunctionId = "014",
                            RoleId = "001"
                        });
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.ServerNode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastEchoTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("agc_server_node", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.ServiceInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlarmUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartBeatMode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeartBeat")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaData")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RegisterTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegisterWay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "ServiceName");

                    b.ToTable("agc_service_info", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.Setting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("agc_setting", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.SysLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LogTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogType")
                        .HasMaxLength(256)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogTime");

                    b.ToTable("agc_sys_log", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("agc_user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            CreateTime = new DateTime(2026, 3, 11, 9, 36, 21, 0, DateTimeKind.Utc),
                            Password = "pRfB26KYvaoEaPRHsdjHYX8zSncNx3NN8Avz3T6JbO0=",
                            Salt = "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6",
                            Source = 0,
                            Status = 0,
                            Team = "",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.UserAppAuth", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Permission")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "UserId");

                    b.ToTable("agc_user_app_auth", (string)null);
                });

            modelBuilder.Entity("AgileConfig.Server.Data.Entity.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("agc_user_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role-001",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = "001",
                            UserId = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
